# import libs
from typing import Any, Dict, List, Literal, Optional
# ! locals
from ...utils.utility import TauCorrelation
from .parameter_core import ENRTLParameterCore
from ..nrtl.parameter_builder import NRTLParameterBuilder


class ENRTLParameterBuilder(ENRTLParameterCore):
    """Resolve ENRTL parameters without treating charge as fitted data."""

    def __init__(
        self,
        components: List[str],
        comp_idx: Dict[str, int],
        datasource: Dict,
        equationsource: Dict,
        **kwargs: Any,
    ) -> None:
        """
        Initialize the ENRTL parameter builder for a fixed component set.

        Parameters
        ----------
        components : List[str]
            Ordered list of true-species component keys.
        comp_idx : Dict[str, int]
            Mapping of component key to its index/position.
        datasource : Dict
            Data source used to resolve model parameters.
        equationsource : Dict
            Equation source used to resolve temperature-dependent correlations.
        **kwargs : Any
            Additional keyword arguments forwarded to the parent classes.
        """
        super().__init__(
            components=components,
            comp_idx=comp_idx,
            datasource=datasource,
            equationsource=equationsource,
            **kwargs,
        )
        # NOTE: reuse the NRTL local-composition (tau_ij/alpha_ij) parameter machinery
        self._nrtl_parameter_builder = NRTLParameterBuilder(
            components=components,
            comp_idx=comp_idx,
            datasource=datasource,
            equationsource=equationsource,
            **kwargs,
        )

    def inputs_generator(
        self,
        temperature: Optional[List[float | str]] = None,
        tau_correlation: TauCorrelation = "gibbs_energy",
        symbol_delimiter: Literal["|", "_"] = "|",
        mixture_ids: Optional[Dict[str, str]] = None,
        include_alpha: bool = True,
        **kwargs: Any,
    ) -> Dict[str, Any]:
        """
        Build the local-composition model inputs (`tau_ij`, `alpha_ij`, ...) by
        delegating to the NRTL parameter builder.

        Parameters
        ----------
        temperature : Optional[List[float | str]]
            `[value, unit]` pair used to evaluate temperature-dependent `tau_ij`.
        tau_correlation : TauCorrelation
            Temperature-dependent correlation used to calculate `tau_ij`.
        symbol_delimiter : Literal["|", "_"]
            Delimiter used to join component-pair keys in diagnostics.
        mixture_ids : Optional[Dict[str, str]]
            Mapping of component key to mixture identifier, if applicable.
        include_alpha : bool
            Whether to include `alpha_ij` in the generated inputs.
        **kwargs : Any
            Additional keyword arguments forwarded to the NRTL parameter builder.

        Returns
        -------
        Dict[str, Any]
            Local-composition model inputs generated by `NRTLParameterBuilder`.
        """
        enrtl_datasource = self.data_source_generator(
            mixture_ids=mixture_ids,
            **kwargs,
        )
        nrtl_compatible_builder = NRTLParameterBuilder(
            components=self.components,
            comp_idx=self.comp_idx,
            datasource={"NRTL": enrtl_datasource},
            equationsource=self.equationsource,
        )

        return nrtl_compatible_builder.inputs_generator(
            temperature=temperature,
            tau_correlation=tau_correlation,
            symbol_delimiter=symbol_delimiter,
            mixture_ids=mixture_ids,
            include_alpha=include_alpha,
            **kwargs,
        )

    def resolve_long_range(self, model_input: Dict[str, Any]) -> Dict[str, Any]:
        """
        Extract and normalize the `long_range` electrostatic parameter block.

        Parameters
        ----------
        model_input : Dict[str, Any]
            Full ENRTL model input; may contain a `"long_range"` sub-dict and/or
            a top-level `"activity_basis"` fallback.

        Returns
        -------
        Dict[str, Any]
            Normalized long-range parameters with keys `model`, `basis`, `A`,
            `B`, `A_phi`, `b`, `ion_size`. Missing values are returned as `None`
            and are validated later by `ENRTLLongRange`.

        Raises
        ------
        TypeError
            If `model_input["long_range"]` is present but not a dictionary.
        """
        long_range = model_input.get("long_range", {})
        if not isinstance(long_range, dict):
            raise TypeError("model_input['long_range'] must be a dictionary")

        # NOTE: basis falls back to top-level activity_basis, then defaults to molality
        return {
            "model": long_range.get("model", "pitzer_debye_huckel"),
            "basis": long_range.get("basis", model_input.get("activity_basis", "molality")),
            "A": long_range.get("A"),
            "B": long_range.get("B"),
            "A_phi": long_range.get("A_phi"),
            "b": long_range.get("b"),
            "ion_size": long_range.get("ion_size"),
        }
